name: myiproject
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_messaging: ^11.2.5
  firebase_storage: ^10.2.5
  firebase_core: ^1.11.0
  firebase_database: ^9.0.5
  fluttertoast: ^8.0.8
  email_validator: ^2.0.1
  cached_network_image: ^3.2.0
  permission_handler: ^8.3.0
  google_fonts: ^2.2.0
  firebase_auth: ^3.3.5
  auto_size_text: ^3.0.0
  phone_number: ^0.12.0+1
  intl: ^0.17.0
  http: ^0.13.4
  http_parser: ^4.0.0
  image_picker: ^0.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/start.png
    - assets/img/signin.png
    - assets/img/reg.png
    - assets/img/hand.png
    - assets/img/home.png
